dist: bionic
language: csharp
mono: none
dotnet: 2.2.105

before_install:
    - wget https://cdn.rage.mp/lin/bridge-linux-037.tar.gz -O bridge.tar.gz
    - tar xf bridge.tar.gz
    - 

script:
    - dotnet restore
    - dotnet build bridge/resources/RPServer/RPServer.csproj
